<?php
// 模块信息
return [
    'infro' =>[
  'name' => 'b2b2c',
  'title' => '商城',
  'identifier' => 'com.chouchoutian.www',
  'icon' => 'fa fa-shopping-cart',
  'description' => '多商铺商城模块',
  'author' => '仇仇天',
  'author_url' => 'http://www.chouchoutian.com',
  'version' => '1.0.0',
  'need_module' => [
    [
      'admin',
      'admin.worldtreephp.module',
      '1.0.0',
    ],
  ],
  'need_plugin' => [],
  'tables' => [],
  'database_prefix' => '',
],
    'config'=>[
        'group'=>[],
        'info' =>[
  [
    'id' => 41,
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_verify',
    'title' => 'b2b2商品是否需要审核',
    'group' => '',
    'type' => 'switch',
    'value' => '',
    'options' => '{"on_text":"是","off_text":"否","on_value":"1","off_value":0}',
    'attribute' => '',
    'tips' => '商家发布商品是否需要平台审核才能发布，调用方式：<code>config(\'b2b2c_goods_verify\']</code>',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 1,
    'create_time' => 1576054230,
    'update_time' => 1578577985,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 46,
    'module' => 'b2b2c',
    'name' => 'test_text',
    'title' => '单行文本',
    'group' => '',
    'type' => 'text',
    'value' => 'asd',
    'options' => '[]',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578392988,
    'update_time' => 1578392988,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 47,
    'module' => 'b2b2c',
    'name' => 'test_sderrtte',
    'title' => '多行',
    'group' => '',
    'type' => 'textarea',
    'value' => 'asd',
    'options' => '[]',
    'attribute' => '',
    'tips' => 'asdasd',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578471751,
    'update_time' => 1578471751,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 48,
    'module' => 'b2b2c',
    'name' => 'test_sadsasdas',
    'title' => '静态文本',
    'group' => '',
    'type' => 'static',
    'value' => 'asdasdasd',
    'options' => '[]',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578472569,
    'update_time' => 1579329074,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 49,
    'module' => 'b2b2c',
    'name' => 'test_sserer',
    'title' => ' 密码',
    'group' => '',
    'type' => 'password',
    'value' => 'asdasdasdasd',
    'options' => '[]',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578472659,
    'update_time' => 1578472659,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 50,
    'module' => 'b2b2c',
    'name' => 'test_lsererrt',
    'title' => '单图',
    'group' => '',
    'type' => 'image',
    'value' => '',
    'options' => '{"storage_path":"seasdasd"}',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578476608,
    'update_time' => 1591759326,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 51,
    'module' => 'b2b2c',
    'name' => 'test_lseedd',
    'title' => '复选框',
    'group' => '',
    'type' => 'checkbox',
    'value' => '1,2',
    'options' => '[{"title":"asd","value":"1"},{"title":"dsad","value":"2"},{"title":"asdasd","value":"3"},{"title":"sdsad","value":"4"}]',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578491460,
    'update_time' => 1578491460,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 52,
    'module' => 'b2b2c',
    'name' => 'test_lasddd',
    'title' => '单选框',
    'group' => '',
    'type' => 'radio',
    'value' => '2',
    'options' => '[{"title":"阿三大苏打","value":"1"},{"title":"爱上的人仍然","value":"2"},{"title":"阿三大苏打","value":"3"},{"title":"深入探讨","value":"4"}]',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578491521,
    'update_time' => 1578491521,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 53,
    'module' => 'b2b2c',
    'name' => 'test_lssrrt',
    'title' => '日期',
    'group' => '',
    'type' => 'date',
    'value' => '1135872000',
    'options' => '[]',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578491598,
    'update_time' => 1581143294,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 54,
    'module' => 'b2b2c',
    'name' => 'test_sdasrer',
    'title' => '时间',
    'group' => '',
    'type' => 'time',
    'value' => '1578520980',
    'options' => '[]',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578492411,
    'update_time' => 1581143296,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 55,
    'module' => 'b2b2c',
    'name' => 'test_asdasd',
    'title' => '日期时间',
    'group' => '',
    'type' => 'datetime',
    'value' => '1578535800',
    'options' => '[]',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578493528,
    'update_time' => 1581143298,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 56,
    'module' => 'b2b2c',
    'name' => 'test_ssxxx',
    'title' => ' 日期范围',
    'group' => '',
    'type' => 'daterange',
    'value' => '1578672000,1578672000',
    'options' => '[]',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578495855,
    'update_time' => 1578495855,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 57,
    'module' => 'b2b2c',
    'name' => 'test_sererer',
    'title' => '开关',
    'group' => '',
    'type' => 'switch',
    'value' => '0',
    'options' => '{"on_text":"开","off_text":"关","on_value":"1","off_value":0}',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578498516,
    'update_time' => 1578498516,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 58,
    'module' => 'b2b2c',
    'name' => 'test_asdasdsss',
    'title' => '数组',
    'group' => '',
    'type' => 'array',
    'value' => '{"asads":"asdasdasd"}',
    'options' => '[]',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578498587,
    'update_time' => 1578498587,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 59,
    'module' => 'b2b2c',
    'name' => 'test_sseee',
    'title' => '下拉框',
    'group' => '',
    'type' => 'select',
    'value' => '2',
    'options' => '[{"title":"撒大苏打","value":"1"},{"title":"啊实打实打算","value":"2"},{"title":"啊实打实大苏打","value":"3"},{"title":"啊实打实大苏打","value":"4"}]',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578498844,
    'update_time' => 1578498844,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 60,
    'module' => 'b2b2c',
    'name' => 'test_asdsxxbbnmnm',
    'title' => '多图',
    'group' => '',
    'type' => 'images',
    'value' => 'uploads/seerer/f6986fb2bec389a4777b3f3da0552ed6.jpg,uploads/seerer/37ee55a28a488db1042665ae3d26c345.jpg,uploads/seerer/7119edea2e01cc3122f78396ac361fcc.jpg',
    'options' => '{"storage_path":"seerer"}',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578539277,
    'update_time' => 1578539277,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 61,
    'module' => 'b2b2c',
    'name' => 'test_asdasdasd',
    'title' => '多图',
    'group' => '',
    'type' => 'text',
    'value' => '',
    'options' => '[]',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578542474,
    'update_time' => 1578542474,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 62,
    'module' => 'b2b2c',
    'name' => 'test_aserrtff',
    'title' => '单文件',
    'group' => '',
    'type' => 'file',
    'value' => 'uploads/testfile/432f643bd1fe911f081e034005e3cbcf.mp4',
    'options' => '{"storage_path":"testfile"}',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578559668,
    'update_time' => 1578559668,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 63,
    'module' => 'b2b2c',
    'name' => 'test_aserrtffs',
    'title' => '多文件',
    'group' => '',
    'type' => 'files',
    'value' => 'uploads/testfiles/55d9c928aa2f3301fffd43e98d962cdf.jpg,uploads/testfiles/7ed73043f6970fba3306b5cab6c79ada.jpg,uploads/testfiles/30cd75d88cc0da60910c48741efb91ff.jpg',
    'options' => '{"storage_path":"testfiles"}',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578562935,
    'update_time' => 1578562935,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 64,
    'module' => 'b2b2c',
    'name' => 'test_numberesa',
    'title' => '数字',
    'group' => '',
    'type' => 'number',
    'value' => '',
    'options' => '{"min":"","max":"","step":""}',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578574841,
    'update_time' => 1578574841,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 65,
    'module' => 'b2b2c',
    'name' => 'test_asdadrccc',
    'title' => '百度编辑器',
    'group' => '',
    'type' => 'ueditor',
    'value' => '<p>&lt;p&gt;&amp;lt;p&amp;gt;&amp;amp;lt;p&amp;amp;gt;&amp;amp;amp;lt;p&amp;amp;amp;gt;asdasdasd&amp;amp;amp;lt;/p&amp;amp;amp;gt;&amp;amp;lt;/p&amp;amp;gt;&amp;lt;/p&amp;gt;&lt;/p&gt;</p>',
    'options' => '[]',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578574961,
    'update_time' => 1578574961,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 66,
    'module' => 'b2b2c',
    'name' => 'test_asdasdassss',
    'title' => '取色器',
    'group' => '',
    'type' => 'colorpicker',
    'value' => '#d12222',
    'options' => '[]',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578575962,
    'update_time' => 1578575962,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
  [
    'id' => 67,
    'module' => 'b2b2c',
    'name' => 'test_Asderasd',
    'title' => '标签',
    'group' => '',
    'type' => 'tags',
    'value' => 'asdasd,asdad,asd,asdasda,da,dada,dadad,啊实打实大苏打',
    'options' => '[]',
    'attribute' => '',
    'tips' => '',
    'ajax_url' => '',
    'format' => '',
    'option' => '',
    'is_hide' => 0,
    'create_time' => 1578577111,
    'update_time' => 1578577111,
    'sort' => 100,
    'status' => 1,
    'configs' => NULL,
  ],
]
    ],
    'cache'=>[],
    'action'=>[
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_class_add',
    'title' => 'b2b2c商品分类新增',
    'remark' => 'b2b2c_goods_class_add',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_class_edit',
    'title' => 'b2b2c商品分类编辑',
    'remark' => '商品分类编辑',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_class_del',
    'title' => 'b2b2c商品分类删除',
    'remark' => '商品分类删除',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_class_tag_edit',
    'title' => 'b2b2c商品分类标签编辑',
    'remark' => '商品分类标签编辑',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_class_tag_reset',
    'title' => 'b2b2c商品分类标签重置',
    'remark' => '商品分类标签重置',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_class_tag_update',
    'title' => 'b2b2c商品分类标签更新',
    'remark' => '商品分类标签更新',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_class_import',
    'title' => 'b2b2c商品分类导入',
    'remark' => '商品分类导入',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_class_export',
    'title' => 'b2b2c商品分类导出',
    'remark' => '商品分类导出',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_brand_edit',
    'title' => 'b2b2c商品品牌编辑',
    'remark' => '商品品牌编辑',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_brand_add',
    'title' => 'b2b2c商品品牌新增',
    'remark' => '商品品牌新增',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_brand_del',
    'title' => 'b2b2c商品品牌删除',
    'remark' => '商品品牌删除',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_brand_examine',
    'title' => 'b2b2c商品品牌审核',
    'remark' => 'b2b2c商品品牌审核',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_type_edit',
    'title' => 'b2b2c商品类型编辑',
    'remark' => 'b2b2c商品类型编辑',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_type_add',
    'title' => 'b2b2c商品类型新增',
    'remark' => 'b2b2c商品类型新增',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_type_del',
    'title' => 'b2b2c商品类型删除',
    'remark' => 'b2b2c商品类型删除',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_spec_add',
    'title' => 'b2b2bc商品规格新增',
    'remark' => 'b2b2bc商品规格新增',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_spec_edit',
    'title' => 'b2b2c商品规格编辑',
    'remark' => 'b2b2c商品规格编辑',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_spec_del',
    'title' => 'b2b2c商品规格删除',
    'remark' => 'b2b2c商品规格删除',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_type_attribute_del',
    'title' => 'b2b2c商品类型属性删除',
    'remark' => 'b2b2c商品类型属性删除',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_type_attribute_add',
    'title' => 'b2b2c商品类型属性新增',
    'remark' => 'b2b2c商品类型属性新增',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_type_attribute_edit',
    'title' => 'b2b2c商品类型属性编辑',
    'remark' => 'b2b2c商品类型属性编辑',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_type_custom_edit',
    'title' => 'b2b2c商品类型自定义属性编辑',
    'remark' => 'b2b2c商品类型自定义属性编辑',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_type_custom_add',
    'title' => 'b2b2c商品类型自定义属性新增',
    'remark' => 'b2b2c商品类型自定义属性新增',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_type_custom_del',
    'title' => 'b2b2c商品类型自定义属性删除',
    'remark' => 'b2b2c商品类型自定义属性删除',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_type_attribute_value_edit',
    'title' => 'b2b2c商品类型属性值编辑',
    'remark' => 'b2b2c商品类型属性值编辑',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_type_attribute_value_add',
    'title' => 'b2b2c商品类型属性值新增',
    'remark' => 'b2b2c商品类型属性值新增',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_type_attribute_value_del',
    'title' => 'b2b2c商品属性值删除',
    'remark' => 'b2b2c商品属性值删除',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_state',
    'title' => 'b2b2c商品下架',
    'remark' => 'b2b2c商品下架',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_verify',
    'title' => 'b2b2bc商品审核',
    'remark' => 'b2b2bc商品审核',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_setting',
    'title' => 'b2b2c商品设置',
    'remark' => 'b2b2c商品设置',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_album_del',
    'title' => 'b2b2c相册删除',
    'remark' => 'b2b2c相册删除',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_album_pic_del',
    'title' => 'b2b2c相册图片删除',
    'remark' => 'b2b2c相册图片删除',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_album_video_del',
    'title' => 'b2b2c视频空间删除',
    'remark' => 'b2b2c视频空间删除',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_album_video_videos_d',
    'title' => 'b2b2c视频删除',
    'remark' => 'b2b2c视频删除',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_recommend_add',
    'title' => 'b2b2c商品推荐新增',
    'remark' => 'b2b2c商品推荐新增',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_recommend_del',
    'title' => 'b2b2c商品推荐删除',
    'remark' => 'b2b2c商品推荐删除',
  ],
  [
    'module' => 'b2b2c',
    'name' => 'b2b2c_goods_goods_class_nav_edit',
    'title' => 'b2b2c商品分类导航编辑',
    'remark' => 'b2b2c商品分类导航编辑',
  ],
],
    'menus' =>[
  [
    'title' => '商城',
    'icon' => 'fa fa-fw fa-shopping-cart',
    'url_value' => '',
    'url_target' => '_self',
    'is_hide' => 0,
    'sort' => 4,
    'status' => 1,
    'child' => [
      [
        'title' => '商品',
        'icon' => 'fa fa-fw fa-shopping-basket',
        'url_value' => '',
        'url_target' => '_self',
        'is_hide' => 0,
        'sort' => 0,
        'status' => 1,
        'child' => [
          [
            'title' => '商品管理',
            'icon' => 'fa fa-fw fa-shopping-basket',
            'url_value' => 'b2b2c/goods/index',
            'url_target' => '_self',
            'is_hide' => 0,
            'sort' => 0,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_value' => 'b2b2c/goods/add',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_value' => 'b2b2c/goods/edit',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_value' => 'b2b2c/goods/del',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '查看SPU',
                'icon' => '',
                'url_value' => 'b2b2c/goods/seespu',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '下架',
                'icon' => '',
                'url_value' => 'b2b2c/goods/state',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '审核',
                'icon' => '',
                'url_value' => 'b2b2c/goods/verify',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '商品设置',
                'icon' => '',
                'url_value' => 'b2b2c/goods/goodssetting',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '导出',
                'icon' => '',
                'url_value' => 'b2b2c/goods/export',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '分类管理',
            'icon' => 'fa fa-fw fa-th',
            'url_value' => 'b2b2c/goods_class/index',
            'url_target' => '_self',
            'is_hide' => 0,
            'sort' => 0,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_value' => 'b2b2c/goods_class/add',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_value' => 'b2b2c/goods_class/edit',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_value' => 'b2b2c/goods_class/del',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '导出',
                'icon' => '',
                'url_value' => 'b2b2c/goods_class/export',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '导入',
                'icon' => '',
                'url_value' => 'b2b2c/goods_class/import',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '商品推荐',
                'icon' => 'fa fa-fw fa-mail-reply-all',
                'url_value' => 'b2b2c/goods_class/recommend',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
                'child' => [
                  [
                    'title' => '新增',
                    'icon' => '',
                    'url_value' => 'b2b2c/goods_class/recommendadd',
                    'url_target' => '_self',
                    'is_hide' => 1,
                    'sort' => 0,
                    'status' => 1,
                  ],
                  [
                    'title' => '编辑',
                    'icon' => '',
                    'url_value' => 'b2b2c/goods_class/recommendedit',
                    'url_target' => '_self',
                    'is_hide' => 1,
                    'sort' => 0,
                    'status' => 1,
                  ],
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_value' => 'b2b2c/goods_class/recommenddel',
                    'url_target' => '_self',
                    'is_hide' => 1,
                    'sort' => 0,
                    'status' => 1,
                  ],
                ],
              ],
              [
                'title' => '编辑分类导航',
                'icon' => '',
                'url_value' => 'b2b2c/goods_class/navedit',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '分类标签管理',
            'icon' => '',
            'url_value' => 'b2b2c/goods_class_tag/index',
            'url_target' => '_self',
            'is_hide' => 1,
            'sort' => 0,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_value' => 'b2b2c/goods_class_tag/edit',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '重置',
                'icon' => '',
                'url_value' => 'b2b2c/goods_class_tag/reset',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '更新',
                'icon' => '',
                'url_value' => 'b2b2c/goods_class_tag/update',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '品牌管理',
            'icon' => 'fa fa-fw fa-bold',
            'url_value' => 'b2b2c/brand/index',
            'url_target' => '_self',
            'is_hide' => 0,
            'sort' => 0,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_value' => 'b2b2c/brand/edit',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '新增',
                'icon' => '',
                'url_value' => 'b2b2c/brand/add',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '导出',
                'icon' => '',
                'url_value' => 'b2b2c/brand/export',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '审核',
                'icon' => '',
                'url_value' => 'b2b2c/brand/examine',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '商品类型',
            'icon' => 'fa fa-fw fa-sitemap',
            'url_value' => 'b2b2c/type/index',
            'url_target' => '_self',
            'is_hide' => 0,
            'sort' => 0,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_value' => 'b2b2c/type/edit',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '新增',
                'icon' => '',
                'url_value' => 'b2b2c/type/add',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_value' => 'b2b2c/type/del',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '关联品牌',
                'icon' => '',
                'url_value' => 'b2b2c/type/brand',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
                'child' => [
                  [
                    'title' => '取关',
                    'icon' => '',
                    'url_value' => 'b2b2c/type/branddel',
                    'url_target' => '_self',
                    'is_hide' => 1,
                    'sort' => 0,
                    'status' => 1,
                  ],
                  [
                    'title' => '关联',
                    'icon' => '',
                    'url_value' => 'b2b2c/type/brandadd',
                    'url_target' => '_self',
                    'is_hide' => 1,
                    'sort' => 0,
                    'status' => 1,
                  ],
                ],
              ],
              [
                'title' => '关联规格',
                'icon' => '',
                'url_value' => 'b2b2c/type/spec',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
                'child' => [
                  [
                    'title' => '取关',
                    'icon' => '',
                    'url_value' => 'b2b2c/type/specdel',
                    'url_target' => '_self',
                    'is_hide' => 1,
                    'sort' => 0,
                    'status' => 1,
                  ],
                  [
                    'title' => '关联',
                    'icon' => '',
                    'url_value' => 'b2b2c/type/specadd',
                    'url_target' => '_self',
                    'is_hide' => 1,
                    'sort' => 0,
                    'status' => 1,
                  ],
                ],
              ],
              [
                'title' => '自定义属性',
                'icon' => '',
                'url_value' => 'b2b2c/type/custom',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
                'child' => [
                  [
                    'title' => '编辑',
                    'icon' => '',
                    'url_value' => 'b2b2c/type/customedit',
                    'url_target' => '_self',
                    'is_hide' => 1,
                    'sort' => 0,
                    'status' => 1,
                  ],
                  [
                    'title' => '新增',
                    'icon' => '',
                    'url_value' => 'b2b2c/type/customadd',
                    'url_target' => '_self',
                    'is_hide' => 1,
                    'sort' => 0,
                    'status' => 1,
                  ],
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_value' => 'b2b2c/type/customdel',
                    'url_target' => '_self',
                    'is_hide' => 1,
                    'sort' => 0,
                    'status' => 1,
                  ],
                ],
              ],
              [
                'title' => '设置属性',
                'icon' => '',
                'url_value' => 'b2b2c/type/attribute',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
                'child' => [
                  [
                    'title' => '编辑',
                    'icon' => '',
                    'url_value' => 'b2b2c/type/attributeedit',
                    'url_target' => '_self',
                    'is_hide' => 1,
                    'sort' => 0,
                    'status' => 1,
                  ],
                  [
                    'title' => '新增',
                    'icon' => '',
                    'url_value' => 'b2b2c/type/attributeadd',
                    'url_target' => '_self',
                    'is_hide' => 1,
                    'sort' => 0,
                    'status' => 1,
                  ],
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_value' => 'b2b2c/type/attributedel',
                    'url_target' => '_self',
                    'is_hide' => 1,
                    'sort' => 0,
                    'status' => 1,
                  ],
                  [
                    'title' => '属性值',
                    'icon' => '',
                    'url_value' => 'b2b2c/type/attributevalue',
                    'url_target' => '_self',
                    'is_hide' => 1,
                    'sort' => 0,
                    'status' => 1,
                    'child' => [
                      [
                        'title' => '新增',
                        'icon' => '',
                        'url_value' => 'b2b2c/type/attributevalueadd',
                        'url_target' => '_self',
                        'is_hide' => 1,
                        'sort' => 0,
                        'status' => 1,
                      ],
                      [
                        'title' => '编辑',
                        'icon' => '',
                        'url_value' => 'b2b2c/type/attributevalueedit',
                        'url_target' => '_self',
                        'is_hide' => 1,
                        'sort' => 0,
                        'status' => 1,
                      ],
                      [
                        'title' => '删除',
                        'icon' => '',
                        'url_value' => 'b2b2c/type/attributevaluedel',
                        'url_target' => '_self',
                        'is_hide' => 1,
                        'sort' => 0,
                        'status' => 1,
                      ],
                    ],
                  ],
                ],
              ],
            ],
          ],
          [
            'title' => '商品规格',
            'icon' => 'fa fa-fw fa-linode',
            'url_value' => 'b2b2c/spec/index',
            'url_target' => '_self',
            'is_hide' => 0,
            'sort' => 0,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_value' => 'b2b2c/spec/edit',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '新增',
                'icon' => '',
                'url_value' => 'b2b2c/spec/add',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_value' => 'b2b2c/spec/del',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '图片空间',
            'icon' => 'fa fa-fw fa-file-photo-o',
            'url_value' => 'b2b2c/albym/index',
            'url_target' => '_self',
            'is_hide' => 0,
            'sort' => 0,
            'status' => 1,
            'child' => [
              [
                'title' => '删除',
                'icon' => '',
                'url_value' => 'b2b2c/albym/del',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '相册图片',
                'icon' => '',
                'url_value' => 'b2b2c/albym/pic',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
                'child' => [
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_value' => 'b2b2c/albym/picdel',
                    'url_target' => '_self',
                    'is_hide' => 1,
                    'sort' => 0,
                    'status' => 1,
                  ],
                ],
              ],
            ],
          ],
          [
            'title' => '视频空间',
            'icon' => 'fa fa-fw fa-video-camera',
            'url_value' => 'b2b2c/albym_video/index',
            'url_target' => '_self',
            'is_hide' => 0,
            'sort' => 0,
            'status' => 1,
            'child' => [
              [
                'title' => '删除',
                'icon' => '',
                'url_value' => 'b2b2c/albym_video/del',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '视频',
                'icon' => '',
                'url_value' => 'b2b2c/albym_video/videos',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
                'child' => [
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_value' => 'b2b2c/albym_video/videosdel',
                    'url_target' => '_self',
                    'is_hide' => 1,
                    'sort' => 0,
                    'status' => 1,
                  ],
                ],
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '选择商品',
        'icon' => '',
        'url_value' => 'b2b2c/goods/choice',
        'url_target' => '_self',
        'is_hide' => 1,
        'sort' => 0,
        'status' => 1,
      ],
      [
        'title' => '店铺',
        'icon' => 'fa fa-fw fa-window-restore',
        'url_value' => '',
        'url_target' => '_self',
        'is_hide' => 0,
        'sort' => 0,
        'status' => 1,
        'child' => [
          [
            'title' => '店铺管理',
            'icon' => 'fa fa-fw fa-window-restore',
            'url_value' => 'b2b2c/store/index',
            'url_target' => '_self',
            'is_hide' => 0,
            'sort' => 0,
            'status' => 1,
            'child' => [
              [
                'title' => '查看',
                'icon' => '',
                'url_value' => 'b2b2c/store/see',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_value' => 'b2b2c/store/del',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_value' => 'b2b2c/store/edit',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '修改经营类目',
                'icon' => '',
                'url_value' => 'b2b2c/store/classedit',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
              [
                'title' => '提醒续费',
                'icon' => '',
                'url_value' => 'b2b2c/store/remind',
                'url_target' => '_self',
                'is_hide' => 1,
                'sort' => 0,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
    ],
  ],
],
];